#!/bin/bash

set -e
set -u

prog=$(basename $0)

. $dir/next.subr

cd $MEMBERWORK/csc444

outfile=$(next_output_file $personality)

echo output file ${outfile}


if [ ${mpi:-no} = no ]; then
	tests="na_test_lat_client"
else
	tests=
fi

tests="${tests} hg_test_rpc_lat hg_test_read_bw hg_test_write_bw"

{
	module load job-step-viewer

	for busy in yes no; do
		for test in $tests; do
			export busy
			export test
			rm -f port.cfg ucx-test-hostname finished-*
			jsrun -n ${nnodes} -a1 -c42 sh ${dir}/${personality}-run
		done
	done
	echo "tests complete" 1>&2
} > $outfile 2>&1
