#!/bin/sh

set -e
set -u

prog=$(basename $0)
prog_head=${prog%%-run}
comm=${prog_head##na-}

# Mercury config
#export HG_NA_LOG_LEVEL=debug
#export HLOG="all=on"
export HLOG_OUTPUT=stderr # ring
#export HLOG_OUTPUT=ring
#export HLOG="tx=on rx=on op_life=on reqwait=on na_completions=on wireup=on"
#export HLOG="wireup_req=on"
#export HLOG="op_life=on reclaim=on"

# UCX config
export UCX_NET_DEVICES="mlx5_0:1"

# protocol              description
#
# ud_v                  Verbs-based ud
# ud_x                  accelerated ud
# rc_v                  Verbs-based rc
# rc_x                  accelerated rc
# rc                    any rc
# ud                    any ud

event=cycles
#event=cs
#event=page-faults

perfcmd()
{
	which=$1
	perfpfx="perf record -F 999 -e $event -g"
	if [ ${mpi:-no} = no ]; then
		echo "$perfpfx -o ${which}.perf --"
	fi
}


hg_build_dir=$HOME/na-ucx/mercury/build

cd $MEMBERWORK/csc444

if [ ${test##hg_} != ${test} ]; then
	opt_x="-x 16"
else
	opt_x=
fi

if [ ${mpi:-no} = yes ]; then
	opt_s=-s
	pfxcmd=
else
	opt_s=
	# allow 10 minutes (600 seconds) for each test to complete
	pfxcmd="timeout -s ABRT 600s"
fi

uname -a
echo parameters UCX_NET_DEVICES=${UCX_NET_DEVICES}
echo perfcmd $(perfcmd sample)
echo nnodes $nnodes mpi ${mpi:-no} busy loop ${busy:-no}

opt_b=
if [ ${busy:-no} = yes ]; then
	opt_b=-b
fi

case ${PMIX_RANK:-other} in
other)
	if [ ${PMIX_RANK:-none} = "none" ]
	then
		echo "Rank (PMIX_RANK) is not set." 1>&2
	else
		echo "Unexpected rank (PMIX_RANK), ${PMIX_RANK}." 1>&2
	fi
	;;
0)
	if [ ${test##na_} != ${test} ]; then
		server=$hg_build_dir/bin/na_test_lat_server
	else
		server=$hg_build_dir/bin/hg_test_server
	fi
	echo "server node: starting $server for $test" 1>&2
	$pfxcmd $(perfcmd ${test}-sv) $server -V ${opt_s} \
	    -c $comm -p ${protocol:-all} ${opt_b} ${opt_x} -H mlx5_0 | \
	    2>&1 | sed -u 's,^,S ,'
	echo "server rank $PMIX_RANK: ${test} complete" 1>&2
	;;
*)
	echo "rank $PMIX_RANK (client)"
	if [ ${mpi:-no} = no ]; then
		echo "client node: awaiting port.cfg for $test" 1>&2
		while [ ! -e port.cfg ]; do
			sleep 1
		done
	fi
	client=$hg_build_dir/bin/$test
	echo "client node: starting $client for $test" 1>&2
	$pfxcmd $(perfcmd ${test}-cl) $client -V ${opt_s} \
	    -c $comm -p ${protocol:-all} ${opt_b} ${opt_x} -H mlx5_0 -l 1000 \
	    2>&1 | sed -u 's,^,C ,'
	echo "client rank $PMIX_RANK: ${test} complete" 1>&2
	;;
esac
