#!/bin/sh
set -e
set -u

export dir=$(pwd)/$(dirname $0)
prog=$(basename $0)
export personality=${prog%%-launch}

if [ $# -gt 0 ]; then
	nclients=$1
	nnodes=$(($nclients + 1))
else
	nnodes=2
fi

export nnodes

tmpdir=$(mktemp -d $HOME/${prog}.XXXXXX)

export cores_per_compute_node=42
batch_slots=1
compute_slots=$((nnodes * cores_per_compute_node))
total_slots=$((batch_slots + compute_slots))

cat > ${tmpdir}/${personality}-job <<EOF
#!/bin/bash
# LSF directives
#BSUB -P CSC444
#BSUB -W 0:10
#BSUB -q debug
#BSUB -csm y
#BSUB -n ${total_slots}
#BSUB -R "1*{select[LN]}+${compute_slots}*{select[((CN)&&(type==any))]span[ptile=${cores_per_compute_node}]cu[type=rack:maxcus=1]}"
#BSUB -J ${personality}-job
#BSUB -o ${personality}-job.%Jo
#BSUB -e ${personality}-job.%Je

${dir}/${personality}-startall
EOF

bsub ${tmpdir}/${personality}-job
